force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BookControllerTestClass.cls
@IsTest
private class BookControllerTestClass 
{
    @IsTest
    static void validateBookDiscount() 
    {
        Book__c book = new Book__c(Name='Behind the Cloud', Price__c=100);
        System.debug('Price before inserting new book: ' + book.Price__c);
        
        insert book;
        
        book = [SELECT Price__c FROM Book__c WHERE Id =: book.Id];
        System.debug('Price after trigger fired: ' + book.Price__c);
        
        System.assertEquals(90, book.Price__c);
    }
}